<?php

namespace ClubBundle\Repository;

use http\Env\Request;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheDescription(Request $request)
    {
        $query=$this->getEntityManager()
            ->createQuery("select so from SponsoringOfferBundle:SponsoringOffer so where so.description='$request'");
        return $query->getResult();

        $query = $this->getEntityManager()
            ->createQuery();
        return $query->getResult();
    }
}
