<?php

namespace UserBundle\Repository;


/**
 * SponsorFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorFileRepository extends \Doctrine\ORM\EntityRepository
{
    public function accept()
    {
        $query1=$this->getEntityManager()
            ->createQuery("update sponsorfile set UserBundle:SponsorFile sf.status='Accepted'");
        return $query1->;
    }
    public function rechercheTitre($titre)
    {
        $query=$this->getEntityManager()
            ->createQuery("select c from ClubBundle:Club c where c.titre='$titre'");
        return $query->getResult();
    }
}