<?php

namespace UserBundle\Repository;


/**
 * SponsorFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorFileRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEntitiesByString($str){
        return $this->getEntityManager()->createQuery(
            'SELECT e FROM UserBundle:SponsorFile e WHERE e.idUser.username LIKE str'
        )->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
}