<?php

namespace EshopBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{ public function myfindAll()
{
    $query=$this->getEntityManager()
        ->createQuery("select p from EshopBundle:Product p");
    return $query->getResult();
}
    public function rechercheTitre($name)
    {
        $query=$this->getEntityManager()
            ->createQuery("select c from EshopBundle:Category c where c.name='$name'");
        return $query->getResult();
    }

}
