blacklist_index:
    path:     /
    defaults: { _controller: "UserBundle:BlackList:index" }
    methods:  GET

blacklist_show:
    path:     /{idEntry}/show
    defaults: { _controller: "UserBundle:BlackList:show" }
    methods:  GET

blacklist_new:
    path:     /new
    defaults: { _controller: "UserBundle:BlackList:new" }
    methods:  [GET, POST]

blacklist_edit:
    path:     /{idEntry}/edit
    defaults: { _controller: "UserBundle:BlackList:edit" }
    methods:  [GET, POST]

blacklist_delete:
    path:     /{idEntry}/delete
    defaults: { _controller: "UserBundle:BlackList:delete" }
    methods:  DELETE
