user_sponsorfile:
    resource: "@UserBundle/Resources/config/routing/sponsorfile.yml"
    prefix:   /sponsorfile

user_blacklist:
    resource: "@UserBundle/Resources/config/routing/blacklist.yml"
    prefix:   /blacklist

user_homepage:
    path:     /
    defaults: { _controller: fos_user.profile.controller:indexAction }

admin_homepage:
    path:     /admin
    defaults: { _controller: fos_user.profile.controller:adminAction }
webservice_users:
    path:     /wsusershowall
    defaults: { _controller: UserBundle:WebService:allUsers }




