<?php


namespace ClientBundle\Repository;


/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{

    public function rechercheEtat($nom)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder(" select f from ClientBundle:Reclamation f where f.nom LIKE :nom");
        return $query->getResult();
    }
    public function myfindAll()
    {
        $query=$this->getEntityManager()
            ->createQuery("select f from ClientBundle:Reclamation f");
        return $query->getResult();
    }
    public function rechercheEtatAdmin($etat)
    {
        $query = $this->getEntityManager()
            ->createQuery("select f from ClientBundle:Reclamation f where f.etat='$etat'");
        return $query->getResult();
    }


}
