lreservation_index:
    path:     /
    defaults: { _controller: "LocataireBundle:LocalReservation:index" }
    methods:  GET

lreservation_show:
    path:     /{idReservation}/show
    defaults: { _controller: "LocataireBundle:LocalReservation:show" }
    methods:  GET
lreservation_edit:
    path:     /{idReservation}/edit
    defaults: { _controller: "LocataireBundle:LocalReservation:edit" }
    methods:  [GET, POST]

lreservation_delete:
    path:     /{idReservation}/delete
    defaults: { _controller: "LocataireBundle:LocalReservation:delete" }
    methods:  DELETE