ulocal_index:
  path:     /
  defaults: { _controller: "LocataireBundle:Local:uindex" }
  methods:  GET
ulocal_show:
    path:     /show/{idLoc}
    defaults: { _controller: "LocataireBundle:Local:ushow" }
    methods:  GET